### PR TITLE
Fix: migration scripts added to the repo (fixes #232)

### LINKED ISSUE #232: Add migration scripts to repo
Part of - https://github.com/adaptlearning/adapt_framework/issues/3631

### PR DESCRIPTION
**Pull request by joe-allen-89**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
#232 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* migration scripts added to the repo (fixes #232)

### CODE REVIEW

File: migrations/v7.js [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+    MCQs = content.filter(({ _component }) => _component === 'mcq');
+    return MCQs.length;
+  });
+  mutateContent('MCQ - modify instruction attribute', async (content) => {
+    MCQs.forEach(MCQ => {
+      if (MCQ.instruction === originalInstruction) MCQ.instruction = 'Choose {{#if _isRadio}}one option{{else}}one or more options{{/if}} then select Submit.';
+    });
+    return true;
+  });
+  mutateContent('MCQ - add ariaQuestion attribute to _items', async (content) => {
```
Comment (chris-steele) [inline migrations/v7.js:19]: Remove `_items` from description

**Review by chris-steele — CHANGES_REQUESTED** [review]
Just done a code review, looks great 👍

File: migrations/v7.js [hunk 2]
```diff
@@ -0,0 +1,137 @@
...
+describe('MCQ - v7.4.3 to v7.5.0', async () => {
+  let MCQs;
+  whereFromPlugin('MCQ - from v7.4.3', { name: 'adapt-contrib-mcq', version: '<7.5.0' });
+  whereContent('MCQ - where MCQ', async (content) => {
+    MCQs = getComponents('mcq');
+    return MCQs.length;
+  });
+  mutateContent('MCQ - add _canShowCorrectness attribute', async (content) => {
+    MCQs.forEach(MCQ => {
+      MCQ._canShowCorrectness = false;
```
Comment (swashbuck) [inline migrations/v7.js:110]: Should `_canShowCorrectness` be set to `true` if `_showMarking` is also `true`? Course creators who enable marking on questions previously saw the button-level marking as well as option-level marking. With `_canShowCorrectness` set to `false`, they would lose the option-level marking which would be unexpected.

Comment (joe-allen-89) [reply migrations/v7.js:110]: That's an interesting point @swashbuck, rather than solely focussing on the default value we should also be aiming for continuity from migrated courses. I think you're right. So if we need to add an additional check to see what _showMarking is equal to before updating.

**Review by chris-steele — APPROVED** [review]
